name: Cobrinha de Contribuição

on:
  push:
    branches:
      - main  # Ou a branch que você estiver usando

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: |
        curl -s https://raw.githubusercontent.com/josuegeraldommfata/josuegeraldommfata/main/output/github-contribution-grid-snake.svg -o github-contribution-grid-snake.svg

    - name: Commitar e enviar animação
      run: |
        git config --global user.name "josé geraldo gomes"
        git config --global user.email "robsonalexmmfata@gmail.com"
        git add github-contribution-grid-snake.svg
        git commit -m "Atualizar animação da cobrinha"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
